version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-3.2.4
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  zabbix-agent:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix_agent
    hostname: zabbix_agent
    ports:
    - "5000:5000"
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-3.2.4
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      ZBX_SERVER_HOST: zabbix-server
      TZ: Asia/Tokyo
    ports:
    - "10000:80"
  mysql:
    image: mysql:5.6.35
    environment:
      MYSQL_ROOT_PASSWORD: password
